#include "my.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>

int main()
{
    printf("test my_char--------\n");
    my_char('A');
    my_char('q');
    printf("\ntest my_str--------\n");
    my_str("Esther");
    printf("\n");
    my_str("Esther Stolbach");
    printf("\n");
    my_str("123");
    printf("\n");
    my_str("J");
    printf("\n");
    my_str(NULL);
    printf("\n");
    my_str('\0');
    printf("\n");
    my_str("Hey in case you are reading this I hope you have a great day! \nPlease go easy on grading us, we worked really hard on this assignment and would rlly like a good grade :) \nanyway I really gotta submit this soo byeeeee");
    printf("\n");
    char *s = "hello";
    my_str(s);
    printf("\n");
    s = NULL;
    my_str(s);
    printf("\ntest my_int--------\n");
    my_int(4);
    printf("\n");
    my_int(0);
    printf("\n");
    my_int(-1);
    printf("\n");
    my_int(-10);
    printf("\n");
    my_int(100);
    printf("\n");
    my_int(-1000);
    printf("\n");
    my_int(2147483647);
    printf("\n");
    my_int(-2147483648);
    printf("\ntest my_num_base--------\n");
    my_num_base(0, NULL);
    printf("\n");
    my_num_base(2147483647, NULL);
    printf("\n");
    my_num_base(-2147483648, NULL);
    printf("\n");
    my_num_base(2147483647, "coffee");
    printf("\n");
    my_num_base(-2147483648, "adjy");
    printf("\n");
    my_num_base(-1, NULL);
    printf("\n");
    my_num_base(-1, "c");
    printf("\n");
    my_num_base(9, "zoom");
    printf("\n");
    my_num_base(0, "hey");
    printf("\n");
    my_num_base(9, ":");
    printf("\n");
    printf("\ntest my_alpha--------\n");
    my_alpha();
    printf("\ntest my_digits--------\n");
    my_digits();
    printf("\ntest my_strindex--------\n");
    int i = my_strindex("banana", 'a');
    my_int(i);
    printf(" result: 1\n");
    i = my_strindex("banana", 'c');
    my_int(i);
    printf(" result: -1\n");
    i = my_strindex(NULL, 'a');
    my_int(i);
    printf(" result: -1\n");
    i = my_strindex('\0', 'z');
    my_int(i);
    printf(" result: -1\n");
    i = my_strindex("apple", 'a');
    my_int(i);
    printf(" result: 0\n");
    i = my_strindex("rivka", 'a');
    my_int(i);
    printf(" result: 4\n");
    i = my_strindex("hey what's up", 'w');
    my_int(i);
    printf(" result: 4\n");
    printf("\ntest my_strrindex--------\n");
    i = my_strrindex("banana", 'a');
    my_int(i);
    printf(" result: 5\n");
    i = my_strrindex("banana", 'c');
    my_int(i);
    printf(" result: -1\n");
    i = my_strrindex(NULL, 'a');;
    my_int(i);
    printf(" result: -1\n");
    i = my_strrindex('\0', 'z');
    my_int(i);
    printf(" result: -1\n");
    i = my_strrindex("apple", 'a');
    my_int(i);
    printf(" result: 0\n");
    i = my_strrindex("rivka", 'a');
    my_int(i);
    printf(" result: 4\n");
    i = my_strrindex("hey what's up", 'a');
    my_int(i);
    printf(" result: 6\n");
    i = my_strrindex("banana", 'a');
    printf("\n");
    my_int(i);
    printf("\ntest my_strlen--------\n");
    i = my_strlen("H");
    my_int(i);
    printf(" result: 1\n");
    i = my_strlen("I want to eat some chocolate!!");
    my_int(i);
    printf(" result: 30\n");
    i = my_strlen("mmhmm");
    my_int(i);
    printf(" result: 5\n");
    i = my_strlen(NULL);
    my_int(i);
    printf(" result: -1\n");
    i = my_strlen('\0');
    my_int(i);
    printf(" result: -1\n");
    char *a = "sleepy";
    i = my_strlen(a);
    my_int(i);
    printf(" result: 6\n");
    a = NULL;
    i = my_strlen(a);
    my_int(i);
    printf(" result: -1\n");
    printf("\ntest my_revstr--------\n");
    char string[] = "abcde";
    int j = my_revstr(string);
    my_int(j);
    printf("  ");
    my_str(string);
    printf("\n");
    char string1[] = "a";
    int j1 = my_revstr(string1);
    my_int(j1);
    printf("  ");
    my_str(string1);
    printf("\n");
    int j2 = my_revstr(NULL);
    my_int(j2);
    printf("\n");
    char string3[] = "\0";
    int j3 = my_revstr(string3);
    my_int(j3);
    printf("\n");
    my_str(string3);
    printf("\n");
    char string4[] = "qwertyuiqop";
    int j4 = my_revstr(string4);
    my_int(j4);
    printf("  ");
    my_str(string4);
    printf("\ntest my_strfind--------\n");
    char hello[] = "hello";
    char l = 'l';
    printf("%s result: llo", my_strfind(hello, l));
    printf("\n");
    printf("%s result: Null", my_strfind(NULL, '\0'));
    printf("\n");
    printf("%s result: Null\n", my_strfind(hello, '\0'));
    printf("%s result: Null", my_strfind(hello, 'k'));
    printf("\n");
    printf("%s result: m", my_strfind("zoom", 'm'));
    printf("\n");
    printf("%s result: Null", my_strfind("\0", l));
    printf("\ntest my_strffind--------\n");
    printf("%s result: lo", my_strrfind(hello, l));
    printf("\n");
    printf("%s result: Null", my_strrfind(NULL, '\0'));
    printf("\n");
    printf("%s result: Null", my_strrfind(hello, 'k'));
    printf("\n");
    printf("%s result: m", my_strrfind("zoom", 'm'));
    printf("\n");
    printf("%s result: Null", my_strrfind("\0", l));
    printf("\n");
    char sleepy[] = "sleepy\0a";
    char ape[] = "ape";
    char apple[] = "apple";
    printf("\ntest my_strcmp--------\n");
    printf("%d result: 1\n", my_strcmp(sleepy, hello));
    printf("%d result: 0\n", my_strcmp(sleepy, sleepy));
    printf("%d result: -1\n", my_strcmp(hello, sleepy));
    printf("%d result: -1\n", my_strcmp("ape", "apple"));
    printf("%d result: -1\n", my_strcmp(NULL, hello));
    printf("%d result: 1\n", my_strcmp(hello, NULL));
    printf("%d result: 0\n", my_strcmp(NULL, NULL));
    printf("%d result: -1\n", my_strcmp("Ape", "apple"));
    printf("\ntest my_strncmp--------\n");
    printf("%d result: 1\n", my_strncmp(sleepy, hello, 1));
    printf("%d result: 0\n", my_strncmp(sleepy, sleepy, 3));
    printf("%d result: 0\n", my_strncmp(hello, sleepy, 0));
    printf("%d result: 0\n", my_strncmp(ape, apple, -2));
    printf("%d result: 0\n", my_strncmp("ape", "apple", 2));
    printf("%d result: -1\n", my_strncmp(NULL, hello, 4));
    printf("%d result: 1\n", my_strncmp(hello, NULL, 10));
    printf("%d result: 0\n", my_strncmp(NULL, NULL, 5));
    printf("%d result: 1\n", my_strncmp("ape", "Apple", 2));
    printf("\ntest my_strcpy--------\n");
    printf("%s result: hello\n", my_strcpy(sleepy, hello));
    printf("%s result: hello\n", my_strcpy(sleepy, sleepy)); //sleepy = hello
    printf("%s result: apple\n", my_strcpy(ape, apple));
    my_str(apple);
    printf("\n%s result: Null\n", my_strcpy(NULL, hello));
    printf("%s result: hello\n", my_strcpy(hello, NULL));
    printf("%s result: Null\n", my_strcpy(NULL, NULL));
    // char *cc = (char*) malloc(7);
    // my_strcpy(cc, "hello");
    // my_strcpy(&cc[l],cc);
    // printf("%s result: hhello", cc);
    char snow[] = "snow";
    char board[] = "board";
    char ski[] = "ski";
    printf("\ntest my_strncpy--------\n");
    printf("%s result: boar\n", my_strncpy(snow, board, 4));
    printf("%s result: board\n", my_strncpy(board, ski, -2));
    printf("%s result: ski\n", my_strncpy(ski, ski, 5));
    printf("%s result: app\n", my_strncpy(hello, apple, 3));
    printf("%s result: NULL\n", my_strncpy(NULL, hello, 0));
    printf("%s result: app\n", my_strncpy(hello, NULL, 2));
    printf("%s result: Null\n", my_strncpy(NULL, NULL, 5));
    printf("\ntest my_strcat--------\n");
    char sle[] = "sleepy";
    char h[] = "hello";
    char sl[] = "sleepy";
    char hi[] = "hi";
    printf("%s result: sleepyhello\n", my_strcat(sle, h));
    printf("%s result: sleepysleepy\n", my_strcat(sl, sl));
    printf("%s result: hellosleepysleepy\n", my_strcat(h, sl)); // sl = sleepysleepy
    printf("%s result: hisleepysleepy\n", my_strcat(hi, sl));
    printf("%s result Null\n", my_strcat(NULL, hello));
    printf("%s result: app\n", my_strcat(hello, NULL)); // hello = app
    printf("%s result: Null\n", my_strcat(NULL, NULL));
    char test[11] = "hello";
    printf("%s result hellohello" , my_strcat(test,test));
    printf("\ntest my_strdup--------\n");
    char *s4 = "abcd";
    char *t4 = my_strdup(s4);
    printf("%s result: abcd\n", t4);
    char *s1 = NULL;
    char *t1 = my_strdup(s1);
    printf("%s result: Null\n", t1);
    char *s2 = "a";
    char *t2 = my_strdup(s2);
    printf("%s result: a\n", t2);
    char *s3 = "abcdefghijklmnopqrstuvwxyz";
    char *t3 = my_strdup(s3);
    printf("%s result: abcdefghijklmnopqrstuvwxyz\n", t3);
    char *s5 = "\0";
    char *t5 = my_strdup(s5);
    printf("%s result: \n", t5);
    printf("\ntest my_strconcat--------\n");
    char *s6 = "abcd";
    char *r6 = "efgh";
    char *t6 = my_strconcat(s6, r6);
    printf("%s result: abcdefgh\n", t6);
    char *t7 = my_strconcat(s6, s6);
    printf("%s result: abcdabcd\n", t7);
    char *t8 = my_strconcat(s6, NULL);
    printf("%s result: abcd\n", t8);
    char *t9 = my_strconcat(NULL, s6);
    printf("%s result: abcd\n", t9);
    char *t10 = my_strconcat(NULL, NULL);
    printf("%s result: NULL\n", t10);
   // char* str1 = "abc";
// char* str2 = "def";
// char* str3 = my_strconcat(str1, str2);
// my_str(str3);
// my_char('\n');
// char* str4 = my_strconcat(str1, str1);
// my_str(str4);
    printf("\ntest my_strnconcat--------\n");
    //char *t11 = my_strnconcat(s6, r6, 4);
    //printf("%s result: abcdefgh\n", t11);
    //char *t12 = my_strnconcat(s6, s6, 2);
    //printf("%s result: abcdab\n", t12);
    
    char s66[] = "abcd";
    char *t13 = my_strnconcat(s66, NULL, 5);
    printf("%s result: abcd\n", t13);
    char *t14 = my_strnconcat(NULL, s66, 0);
    printf("%s result: \n", t14);
    char *t15 = my_strnconcat(NULL, NULL, 10);
    printf("%s result: NULL\n", t15);
    char s7[] = "Pepper";
    char s8[] = "Ora ";
    char *t16 = my_strnconcat(s8,s7, 20);
    printf("%s result: Ora Pepper\n", t16);
    char s88[] = "Ora";
    char *t17 = my_strnconcat(s88,s66, -1);
    printf("%s result: Ora\n", t17);
    char s99[] = "byee";
    char *t18 = my_strnconcat(s99,s99, 3);
    printf("%s result: byeebye\n", t18);
    printf("\ntest my_atoi--------\n");
    printf("%d result: 5\n", my_atoi("5"));
    printf("%d result: -5\n", my_atoi("-5"));
    printf("%d result: 5\n", my_atoi("--5"));
    printf("%d result: -54\n", my_atoi("a-b54sc7-d"));
    printf("%d result: 0\n", my_atoi("abcd"));
    printf("%d result: 0\n", my_atoi(NULL));
    printf("%d result: 0\n", my_atoi(""));
    printf("%d result: 5\n", my_atoi("5--"));
    printf("%d result: 8\n", my_atoi("heya----8"));
    printf("%d result: 9\n", my_atoi("09"));
    printf("%d result: -123\n", my_atoi("-000123"));
    printf("%d result: -54\n", my_atoi("a-0054sc7-d"));
    return 0;
}