#include "list.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <unistd.h>

int main()
{
	printf("~~~~~~~~~~~~~~~~~Test1~~~~~~~~~~~~~~~~~\n");
	struct s_node** head = malloc(sizeof(struct s_node*));
	*head = NULL; 
	// struct s_node** head5 = malloc(sizeof(struct s_node*));
	// *head5 = NULL; 
	int* a = malloc(sizeof(int));
	*a = 6;
	int* b = malloc(sizeof(int));
	*b = 5;
	int* c = malloc(sizeof(int));
	*c = 4;
	int* d = malloc(sizeof(int));
	*d = -1;
	int* e = malloc(sizeof(int));
	*e = 0;
	int* f = malloc(sizeof(int));
	*f = 33;
	int* g = malloc(sizeof(int));
	*g = 218;
	int* h = malloc(sizeof(int));
	*h = 1995;
	int* i = malloc(sizeof(int));
	*i = 13;
	int* j = malloc(sizeof(int));
	*j = 23;
	int* k = malloc(sizeof(int));
	*k = 2;
	// int* l = malloc(sizeof(int));
	// *l = 3;
	struct s_node* na = new_node(a, NULL,NULL);
	struct s_node* nb = new_node(b, NULL,NULL);
	struct s_node* nc = new_node(c, NULL,NULL);
	struct s_node* nd = new_node(d, NULL,NULL);
	struct s_node* ne = new_node(e, NULL,NULL);
	struct s_node* nf = new_node(f, NULL,NULL);
	struct s_node* ng = new_node(g, NULL,NULL);
	struct s_node* nh = new_node(h, NULL,NULL);
	struct s_node* ni = new_node(i, NULL,NULL);
	struct s_node* nj = new_node(j, NULL,NULL);
	//struct s_node* nk = new_node(k, NULL,NULL);
	// struct s_node* nl = new_node(l, NULL,NULL);
	// add_node(nk, head5);
	// printf("Expected: (NULL <- 2 -> NULL)\n");
	// debug_int(nk);
	// printf("\n");
	// remove_last(head5);
	// add_node(nl, head5);
	// debug_int(nl);
	add_node(na, head);
	printf("Expected: (NULL <- 6 -> NULL)\n");
	debug_int(na);
	printf("\n");
	traverse_int(na); 
	printf("\nList lenght: Expexted: 1, Received: %d", count_s_nodes(na));
	add_node_at(nb, head,0);
	printf("\n\nExpected: (NULL <- 5 -> 6), (5 <- 6 -> NULL) \n");
	debug_int(nb);
	printf("\n");
	traverse_int(nb);
	printf("\nList lenght: Expexted: 2, Received: %d", count_s_nodes(nb));
	add_node(nc, head);
	printf("\n\nExpected: (NULL <- 4 -> 5), (4 <- 5 -> 6), (5 <- 6 -> NULL) \n");
	debug_int(nc);
	printf("\n");
	traverse_int(nc);
	printf("\nList lenght: Expexted: 3, Received: %d", count_s_nodes(nc));
	append(nd, head);
	printf("\n\nExpected: (NULL <- 4 -> 5), (4 <- 5 -> 6), (5 <- 6 -> -1), (6 <- -1 -> NULL) \n");
	debug_int(nc);
	printf("\n");
	traverse_int(nc);
	printf("\nList lenght: Expexted: 4, Received: %d", count_s_nodes(nc));
	add_node_at(ne, head, 2);
	printf("\n\nExpected: (NULL <- 4 -> 5), (4 <- 5 -> 0), (5 <- 0 -> 6), (0 <- 6 -> -1), (6 <- -1 -> NULL) \n");
	debug_int(nc);
	printf("\n");
	traverse_int(nc);
	printf("\nList lenght: Expexted: 5, Received: %d", count_s_nodes(nc));
	add_node_at(nf, head, -2);
	add_node_at(ng, head, 5);
	add_node_at(nh, head, 7);
	add_node_at(ni, head, 22);
	add_node_at(nj, head, 4);
	add_elem(((int*) k), head);
	printf("\n\nExpected: (NULL <- 33 -> 4), (33 <- 4 -> 5), (4 <- 5 -> 0), (5 <- 0 -> 23), (0 <- 23 -> 6), (23 <- 6 -> 218), (6 <- 218 -> -1), (218 <- -1 -> 1995), (-1 <- 1995 -> 13), (1995 <- 13 -> NULL) \n");
	debug_int(nd);
	printf("\n");
	traverse_int(*head);
	printf("\nList lenght: Expexted: 10, Received: %d", count_s_nodes(*head));
	remove_node(head);
	remove_node(head);
	printf("\n\nExpected: (NULL <- 5 -> 0), (5 <- 0 -> 23), (0 <- 23 -> 6), (23 <- 6 -> 218), (6 <- 218 -> -1), (218 <- -1 -> 1995), (-1 <- 1995 -> 13), (1995 <- 13 -> NULL) \n");
	debug_int(*head);
	empty_list(head);

	printf("\n~~~~~~~~~~~~~~~~~Test2~~~~~~~~~~~~~~~~~\n");
	struct s_node** head1 = malloc(sizeof(struct s_node*));
	*head1 = NULL; 
	char a1[] = "woohoo";
	char b1[] = "I";
	char c1[] = "Will";
	char d1[] = "Drive";
	char e1[] = "500";
	char f1[] = "Miles.";
	char g1[] = "Lalala";
	char h1[] = "Happy";
	char i1[] = "Birthday";
	char j1[] = "To Me!";
	struct s_node* na1 = new_node(a1, NULL,NULL);
	struct s_node* nb1 = new_node(b1, NULL,NULL);
	struct s_node* nc1 = new_node(c1, NULL,NULL);
	struct s_node* nd1 = new_node(d1, NULL,NULL);
	struct s_node* ne1 = new_node(e1, NULL,NULL);
	struct s_node* nf1 = new_node(f1, NULL,NULL);
	struct s_node* ng1 = new_node(g1, NULL,NULL);
	struct s_node* nh1 = new_node(h1, NULL,NULL);
	struct s_node* ni1 = new_node(i1, NULL,NULL);
	struct s_node* nj1 = new_node(j1, NULL,NULL);

	add_node_at(nj1, head1,4);
	printf("Expected: (NULL <- To Me! -> NULL)\n");
	debug_string(nj1);
	printf("\n");
	traverse_string(nj1); 
	printf("\nList lenght: Expexted: 1, Received: %d", count_s_nodes(nj1));
	add_node(nh1, head1);
	printf("\n\nExpected: (NULL <- Happy -> To Me!), (Happy <- To Me! -> NULL) \n");
	debug_string(nh1);
	printf("\n");
	traverse_string(nh1);
	printf("\nList lenght: Expexted: 2, Received: %d", count_s_nodes(nh1));
	add_node_at(ni1, head1,1);
	printf("\n\nExpected: (NULL <- Happy -> Birthday), (Happy <- Birthday -> To Me!), (Birthday <- To Me! -> NULL) \n");
	debug_string(nh1);
	printf("\n");
	traverse_string(nh1);
	printf("\nList lenght: Expexted: 3, Received: %d", count_s_nodes(nh1));
	append(ng1, head1);
	printf("\n\nExpected: (NULL <- Happy -> Birthday), (Happy <- Birthday -> To Me!), (Birthday <- To Me! -> Lalala), (To Me! <- Lalala -> NULL) \n");
	debug_string(nh1);
	printf("\n");
	traverse_string(nh1);
	printf("\nList lenght: Expexted: 4, Received: %d", count_s_nodes(nh1));
	add_node_at(ne1, head1, 0);
	printf("\n\nExpected: (NULL <- 500 -> Happy), (500 <- Happy -> Birthday), (Happy <- Birthday -> To Me!), (Birthday <- To Me! -> Lalala), (To Me! <- Lalala -> NULL) \n");
	debug_string(ne1);
	printf("\n");
	traverse_string(ne1);
	printf("\nList lenght: Expexted: 5, Received: %d", count_s_nodes(ne1));
	add_node_at(nf1, head1, 1);
	add_node_at(nb1, head1, -99);
	add_node_at(nd1, head1, 1);
	add_node_at(na1, head1, 50);
	add_node_at(nc1, head1, 1);
	printf("\n\nExpected: (NULL <- I -> Will), (I <- Will -> Drive), (Will <- Drive -> 500), (Drive <- 500 -> Miles.), (500 <- Miles. -> Happy), (Miles. <- Happy -> Birthday), (Happy <- Birthday -> To Me!), (Birthday <- To Me! -> Lalala), (To Me! <- Lalala -> woohoo), (Lalala <- woohoo -> NULL) \n");
	debug_string(nb1);
	printf("\n");
	traverse_string(nb1);
	printf("\nList lenght: Expexted: 10, Received: %d", count_s_nodes(nb1));


	printf("\n~~~~~~~~~~~~~~~~~Test3~~~~~~~~~~~~~~~~~\n");
	struct s_node** head2 = malloc(sizeof(struct s_node*));
	*head2 = NULL; 
	char* a2 = malloc(sizeof(char));
	*a2 = 'E';
	char* b2 = malloc(sizeof(char));
	*b2 = 's';
	char* c2 = malloc(sizeof(char));
	*c2 = 't';
	char* d2 = malloc(sizeof(char));
	*d2 = 'i';
	char* e2 = malloc(sizeof(char));
	*e2 = 'e';
	char* f2 = malloc(sizeof(char));
	*f2 = 'c';
	char* g2 = malloc(sizeof(char));
	*g2 = 'o';
	char* h2 = malloc(sizeof(char));
	*h2 = 'l';
	char* i2 = malloc(sizeof(char));
	*i2 = 'b';
	char* j2 = malloc(sizeof(char));
	*j2 = 'a';
	struct s_node* na2 = new_node(a2, NULL,NULL);
	struct s_node* nb2 = new_node(b2, NULL,NULL);
	struct s_node* nc2 = new_node(c2, NULL,NULL);
	struct s_node* nd2 = new_node(d2, NULL,NULL);
	struct s_node* ne2 = new_node(e2, NULL,NULL);
	struct s_node* nf2 = new_node(f2, NULL,NULL);
	struct s_node* ng2 = new_node(g2, NULL,NULL);
	struct s_node* nh2 = new_node(h2, NULL,NULL);
	struct s_node* ni2 = new_node(i2, NULL,NULL);
	struct s_node* nj2 = new_node(j2, NULL,NULL);

	append(nj2, head2);
	printf("Expected: (NULL <- a -> NULL)\n");
	debug_char(nj2);
	printf("\n");
	traverse_char(nj2); 
	printf("\nList lenght: Expexted: 1, Received: %d", count_s_nodes(nj2));
	add_node(nh2, head2);
	printf("\n\nExpected: (NULL <- l -> a), (l <- a -> NULL) \n");
	debug_char(nh2);
	printf("\n");
	traverse_char(nh2);
	printf("\nList lenght: Expexted: 2, Received: %d", count_s_nodes(nh2));
	add_node_at(ni2, head2, 9);
	printf("\n\nExpected: (NULL <- l -> a), (l <- a -> b), (a <- b -> NULL) \n");
	debug_char(nh2);
	printf("\n");
	traverse_char(nh2);
	printf("\nList lenght: Expexted: 3, Received: %d", count_s_nodes(nh2));
	append(ng2, head2);
	printf("\n\nExpected: (NULL <- l -> a), (l <- a -> b), (a <- b -> o), (b <- o -> NULL) \n");
	debug_char(nh2);
	printf("\n");
	traverse_char(nh2);
	printf("\nList lenght: Expexted: 4, Received: %d", count_s_nodes(nh2));
	add_node_at(ne2, head2, 3);
	printf("\n\nExpected: (NULL <- l -> a), (l <- a -> b), (a <- b -> e), (b <- e -> o), (e <- o -> NULL) \n");
	debug_char(nh2);
	printf("\n");
	traverse_char(nh2);
	printf("\nList lenght: Expexted: 5, Received: %d", count_s_nodes(nh2));
	add_node_at(nf2, head2, 0);
	add_node_at(nb2, head2, -99);
	add_node_at(nd2, head2, 1);
	add_node_at(na2, head2, 2);
	add_node_at(nc2, head2, 5);
	printf("\n\nExpected: (NULL <- s -> i), (s <- i -> E), (i <- E -> c), (E <- c -> a), (c <- l -> t), (l <- t -> a), (t <- a -> b), (a <- b -> e), (b <- e -> o), (e <- o -> NULL) \n");
	debug_char(nb2);
	printf("\n");	
	traverse_char(nb2);
	printf("\nList lenght: Expexted: 10, Received: %d", count_s_nodes(nb2));

	printf("\n");

	return 0;

}